"""empty message

Revision ID: 04067d43760f
Revises: c8c0717ecec0
Create Date: 2025-08-28 07:52:27.321842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04067d43760f'
down_revision = 'c8c0717ecec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dateBirth', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Personajes', schema=None) as batch_op:
        batch_op.drop_column('dateBirth')

    # ### end Alembic commands ###
